version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    
    working_directory: ~/proj

    steps:
      - checkout:
          command: git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
          command: export PATH=~/.rakudobrew/bin:$PATH
          command: rakudobrew init
      - build perl6:
          command: rakudobrew build moar
      - build zef:
          command: rakudobrew build zef
      - install deps:
          command: zef install --deps-only .
      - test:
          command: zef test .
