version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              sudo apt install -y libsqlite3-dev git
      - run:
          name: install perl6
          command: |
              ssh-keygen -f id_rsa -t rsa -N ''
              git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
              eval 'export PATH="~/.rakudobrew/bin:$PATH"'
              rakudobrew init
              rakudobrew build moar
              rakudobrew build zef
      - run:
          name: build module deps
          command: |
              eval 'export PATH="~/.rakudobrew/bin:$PATH"'
              rakudobrew rehash
              zef install --deps-only .
      - run:
          name: test module
          command: |
              eval 'export PATH="~/.rakudobrew/bin:$PATH"'
              rakudobrew rehash
              zef test .
