version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    
    working_directory: ~/proj

    steps:
      - checkout

      - run: |
        git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
        export PATH=~/.rakudobrew/bin:$PATH
        rakudobrew init
        rakudobrew build moar
        rakudobrew build zef
        zef install --deps-only .
        zef test .
