version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: 
        command: |
            sudo apt install -y libsqlite3-dev; \
            git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
#      - run: echo 'export PATH="~/.rakudobrew/bin:$PATH"' >> ~/.bashrc
#      - run: . ~/.bashrc; rakudobrew init
#      - run: . ~/.bashrc; rakudobrew build moar
#      - run: . ~/.bashrc; rakudobrew build zef
#      - run: . ~/.bashrc; zef install --deps-only .
#      - run: . ~/.bashrc; zef test .
