version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              sudo apt install -y libsqlite3-dev git
      - run:
          name: install perl6
          command: |
              export PWD=`pwd`
              cd ~
              mkdir bin
              eval 'export PATH="$HOME/bin:$PATH"'
              ssh-keygen -f id_rsa -t rsa -N ''
              git clone https://github.com/rakudo/rakudo rak
              cd rak
              perl Configure.pl --gen-moar --gen-nqp --backends=moar --prefix=$HOME
              make
              sudo make install
              cd ..
              git clone https://github.com/ugexe/zef.git zef
              cd zef
              perl6 -Ilib bin/zef install .
              cd ..
              cd "$PWD"
              zef install --deps-only .
              zef test .
