version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              sudo apt install -y libsqlite3-dev git
      - run:
          name: install perl6
          command: |
              export PWD=`pwd`
              mkdir $HOME/bin
              eval 'export PATH="$HOME/bin:$PATH"'
              ssh-keygen -f id_rsa -t rsa -N ''
              git clone https://github.com/rakudo/rakudo $HOME/rak
              cd $HOME/rak
              perl Configure.pl --gen-moar --gen-nqp --backends=moar --prefix=$HOME
              make
              sudo make install
              cd $HOME
              git clone https://github.com/ugexe/zef.git $HOME/zef
              cd $HOME/zef
              perl6 -Ilib bin/zef install .
              eval 'export PATH="$HOME/.perl6/bin:$PATH"'
              cd "$PWD"
              zef install --deps-only .
              zef test .
