version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      #- image: sqlite
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: sudo apt search sqlite
      - run: sudo apt install -y libsqlite3-dev
      - run: git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
      - run: export PATH=~/.rakudobrew/bin:$PATH
      - run: rakudobrew init
      - run: rakudobrew build moar
      - run: rakudobrew build zef
      - run: zef install --deps-only .
      - run: zef test .
