version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-0
      - run: git clone https://github.com/tadzik/rakudobrew ~/.rb
      - run: ~/.rb/bin/rakudobrew init
      - run: ~/.rb/bin/rakudobrew build moar
      - run: ~/.rb/bin/rakudobrew build zef
      - run: find ~/.rb/
      - run: zef install --deps-only .
      - run: zef test .
