version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run:
        name: install system deps
        command: |
            sudo apt install -y libsqlite3-dev
            git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
            eval 'export PATH="~/.rakudobrew/bin:$PATH"' ; echo $PATH
            rakudobrew init
            rakudobrew build moar
            rakudobrew build zef
            zef install --deps-only .
            zef test .
      - run: echo 'thank you for watching'
