version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              sudo apt install -y libsqlite3-dev git
      - run:
          name: install perl6
          command: |
              export RPWD=`pwd`
              mkdir $HOME/bin
              eval 'export PATH="$HOME/bin:$PATH"'
              ssh-keygen -f id_rsa -t rsa -N ''
              git clone https://github.com/rakudo/rakudo $HOME/rak
              cd $HOME/rak
              perl Configure.pl --gen-moar --gen-nqp --backends=moar --prefix=$HOME
              make
              sudo make install
              cd $HOME
              git clone https://github.com/ugexe/zef.git $HOME/zef
              cd $HOME/zef
              export BP=`perl6 -Ilib bin/zef install . | grep -A 1 'bin/ script' | tail -n 1`
              echo "installed to $BP"
              eval 'export PATH="$BP:$PATH"'
              echo "cd "'"'"$RPWD"'"'
              cd "$RPWD"
              echo 'testing...';
              zef install --deps-only .
              zef test .
