version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    
    working_directory: ~/proj

    steps:
      - checkout

      - run:
          command: git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
          command: export PATH=~/.rakudobrew/bin:$PATH
          command: rakudobrew init
          command: rakudobrew build moar
          command: rakudobrew build zef
          command: zef install --deps-only .
          command: zef test .
