version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
    
    working_directory: ~/proj

    steps:
      - checkout

      - run:
          command: git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
          command: export PATH=~/.rakudobrew/bin:$PATH
          command: rakudobrew init
      - build perl6

      - run:
          command: rakudobrew build moar

      - build zef

      - run:
          command: rakudobrew build zef
      - install deps

      - run:
          command: zef install --deps-only .
      - test

      - run:
          command: zef test .
