version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    
    working_directory: ~/proj

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev
      - run: git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
      - run: echo 'export PATH="~/.rakudobrew/bin:$PATH"' >> ~/.bashrc
      - run: rakudobrew init
      - run: rakudobrew build moar
      - run: rakudobrew build zef
      - run: zef install --deps-only .
      - run: zef test .
